### ISSUE TITLE
Keychain minder does not accept password El Capitan 11.3

### ISSUE THREAD

**Issue by SillySalamander** [google/macops-keychainminder#10]
Keychain minder is not accepting correct password in either forgot password or know password options.

**Comment by russellhancox** [comment]
Are the affected users' accounts 'Standard' non-admin accounts?

**Comment by SillySalamander** [comment]
hey! 

they are standard users and network accounts

to simulate I changed the users password directly in active directory, so that the user logs in with a different password than their keychain. keychainminder comes up first thing in front of everything (awesome) but the password does not work. I'll try with an admin account now and let you know.

**Comment by russellhancox** [comment]
Oddly, we just noticed this issue ourselves a few minutes ago and have a fix prepared. Watch this space!

**Comment by SillySalamander** [comment]
haha wow thats awesome. how ironic that free software is better supported than Apples OS or anything Microsoft. thank you very much

**Comment by tburgin** [comment]
@SillySalamander This latest pull request should clear up the issue completely. Once approved we will post a new release and binaries.
-  https://github.com/google/macops-keychainminder/pull/12

**Comment by ScarabMonkey** [comment]
Any news on a new release?

**Comment by tburgin** [comment]
Just posted [v1.6](https://github.com/google/macops-keychainminder/releases/tag/v1.6)
