### ISSUE TITLE
Uninstall doesn't revernt the security box to the new style

### ISSUE THREAD

**Issue by jardhug** [google/macops-keychainminder#15]
I uninstalled keychain minder and the security box at screen saver is staying as the old style. How can I revert it back to the El Capitan lock screen?

Thanks,

**Comment by russellhancox** [comment]
You could re-install and then uninstall again passing `--restore-screensaver` to uninstall.sh. 

_Or_, the easy way:

``` sh
sudo security authorizationdb write system.login.screensaver use-login-window-ui
```
