### ISSUE TITLE
Screensaver login UI stays old after uninstall

### ISSUE THREAD

**Issue by nilsbyte** [google/macops-keychainminder#18]
After uninstalling on 10.11.5 the screensaver still displays the old-style user-password dialog instead of the loginwindow. How can I revert this change?

**Comment by russellhancox** [comment]
The uninstaller in previous versions didn't revert the screensaver properly, the latest does. You could re-install and then uninstall again passing --restore-screensaver to uninstall.sh.

_Or_, the easy way:

`sudo security authorizationdb write system.login.screensaver use-login-window-ui`

**Comment by nilsbyte** [comment]
I used the latest installer as it did not change the last 4 months. Can you check the script?
However, your command worked. Thanks.
