### ISSUE TITLE
Pre-packaged version?

### ISSUE THREAD

**Issue by scottlep** [google/macops-keychainminder#19]
Hi all. I am unfamiliar with The Luggage but have still tried to package Keychain Minder with no success. Does anyone have a pre-packaged version of the latest Keychain Minder that they could share?

Thanks!
Scott

**Comment by scottlep** [comment]
Duh, nevermind. I swear I looked around here for it, but of course as soon as I submitted the above message I found it. Sorry

**Comment by clburlison** [comment]
From the Code tab at the top of this repo you need to click on "Releases". Here is a link https://github.com/google/macops-keychainminder/releases. Prebuilt packages are shown on that page.

**Comment by scottlep** [comment]
Yeah, thanks. I found it about 5 seconds after I sent my first message. Sorry to bug everyone :)

~S
