### ISSUE TITLE
Pre-compiled Package?

### ISSUE THREAD

**Issue by kennyedgar** [google/macops-keychainminder#7]
Do you supply an already compiled and packaged mac installer for this?

Thanks,
Ken

**Comment by russellhancox** [comment]
We haven't so far but I don't see any reason that we couldn't.

**Comment by clburlison** [comment]
I would love this feature as well. Then we could use autopkg to pull updates automatically!

## 

Clayton Burlison

**Comment by russellhancox** [comment]
Done. https://github.com/google/macops-keychainminder/releases
