### ISSUE TITLE
Incorrect uninstall path in readme

### ISSUE THREAD

**Issue by opragel** [google/macops-keychainminder#9]
Hi there,

Noticed that the keychainminder readme gives this path to the uninstallation script:

`/Library/SecurityAgentPlugins/KeychainMinder.bundle/Contents/Resources/uninstall.sh`

Believe this should actually be:

`/Library/Security/SecurityAgentPlugins/KeychainMinder.bundle/Contents/Resources/uninstall.sh`

**Comment by russellhancox** [comment]
Fixed with 81922f4cf0b2b585af334109dc8ab323777f9336
